version: '3'
services:
    mysql:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=Betpark@@??22
            - MYSQL_DATABASE=lords
            - MYSQL_USER=lordproe_root
            - MYSQL_PASSWORD=Betpark22222
    redis:
        image: 'redis:latest'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        depends_on:
           - mysql
        environment: 
            WAIT_HOSTS: mysql:3306
        environment: 
            - DB_USERNAME=lordproe_root
            - DB_PASSWORD=Betpark22222
            - HOST=mysql
            - DB_NAME=lords
            - DB_PORT=3306
            - CACHE_HOST=redis
            - CACHE_PORT=6379
            - SECRET=65978c012725116b4082d9e173c6a58fc18f5487bc5188bbd939038609a61a52979a550ce4cecb505f674deb6cf8027ca86f132daeac7a909d7599f82ece6184
            - NODE_ENV=development
    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "80:80"
